/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/* BSD */
/* #undef BSD */

/* Darwin */
/* #undef DARWIN */

/* Define 1 to disable MAC address vendor resolution. */
/* #undef DISABLE_VENDOR */

/* FreeBSD */
/* #undef FREEBSD */

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Have PCAP Header File */
#define HAVE_PCAP_H 1

/* Define to 1 if you have the <pcre.h> header file. */
#define HAVE_PCRE_H 1

/* Define to 1 if you have the <signal.h> header file. */
#define HAVE_SIGNAL_H 1

/* Define to 1 if you have the <stdarg.h> header file. */
#define HAVE_STDARG_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdio.h> header file. */
#define HAVE_STDIO_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the `strlcat' function. */
/* #undef HAVE_STRLCAT */

/* Define to 1 if you have the `strlcpy' function. */
/* #undef HAVE_STRLCPY */

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <time.h> header file. */
#define HAVE_TIME_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Directory containing binary files (ex. 'bin/'). */
#define INSTALL_BINDIR "/usr/local/bin"

/* Directory containing data files (ex. 'share/'). */
#define INSTALL_DATADIR "/usr/local/share"

/* Base directory for PADS system dependant installation. */
#define INSTALL_EXECPREFIX "/usr/local"

/* Directory containing library files (ex. 'lib/). */
#define INSTALL_LIBDIR "/usr/local/lib"

/* Base directory of PADS installation. */
#define INSTALL_PREFIX "/usr/local"

/* Directory containing configuration files (ex. 'etc/'). */
#define INSTALL_SYSCONFDIR "/usr/local/etc"

/* Linux */
#define LINUX 1

/* Operating System */
#define OS LINUX

/* "Operating System Type" */
#define OS_TYPE "x86_64-unknown-linux-gnu"

/* Name of package */
#define PACKAGE "pads"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "matt@mattshelton.com"

/* Define the date of this release. */
#define PACKAGE_DATE "06/17/05"

/* Define to the full name of this package. */
#define PACKAGE_NAME "pads"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "pads 1.2"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "pads"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.2"

/* Define as the return type of signal handlers (`int' or `void'). */
#define RETSIGTYPE void

/* Solaris */
/* #undef SOLARIS */

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Unknown OS */
/* #undef UNKNOWN_OS */

/* Version number of package */
#define VERSION "1.2"

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */
